import org.springframework.boot.gradle.tasks.bundling.BootJar

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'com.github.node-gradle.node' version '7.0.2'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('bootJar', BootJar) {
    dependsOn "copyReactBuildFiles"

    mainClass = "com.example.server.DemoApplication"
    archiveBaseName = "demo"
}

tasks.named('bootRun') {
    systemProperty 'spring.profiles.active', 'dev'
}

sourceSets {
    main {
        resources {
            srcDirs = ["$projectDir/src/main/resources"]
        }
    }
}

def appDir = "$rootDir/app"

// Node.js 플러그인 설정
node {
    version = '18.20.2'  // 원하는 Node.js 버전
    download = true  // 자동으로 Node.js 다운로드
    workDir = file("${project.projectDir}/.gradle/nodejs")
    nodeProjectDir = file(appDir)
}

// React 빌드 메모리 설정 (t2.small 인스턴스: 메모리 절약 모드)
tasks.named('npm_run_build').configure {
    environment = [
        'NODE_OPTIONS': '--max_old_space_size=1024'  // Node.js 최대 메모리를 1GB로 제한
    ]
    outputs.dir("$appDir/build")
}

tasks.register('copyReactBuildFiles', Copy) {
    dependsOn "npm_run_build"
    from "$appDir/build"
    into "$buildDir/resources/main/static"
}

tasks.named('processResources') {
    dependsOn "copyReactBuildFiles"
}